# Generated by Django 4.2.6 on 2025-10-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("period", models.CharField(max_length=50)),
                ("total_income", models.FloatField()),
                ("gross_profit", models.FloatField()),
                ("admin_expenses", models.FloatField()),
                ("distribution_costs", models.FloatField()),
                ("finance_costs", models.FloatField()),
                ("net_profit", models.FloatField()),
                ("revenue_growth_rate", models.FloatField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FinancialScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("net_profit_margin", models.FloatField()),
                ("expense_ratio", models.FloatField()),
                ("gross_profit_margin", models.FloatField()),
                ("finance_cost_ratio", models.FloatField()),
                ("weighted_score", models.FloatField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("suggestion", models.TextField(blank=True, null=True)),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.financialrecord",
                    ),
                ),
            ],
        ),
    ]
